### PR TITLE
from airtest.core.api import the undefined names

### PR DESCRIPTION
**Pull request by cclauss**
Should fix the flake8 tests.

### CODE REVIEW

**Comment by Meteorix** [comment]
@cclauss 

Actually, we use *hidden* import here for simplicity, so that QA engineers with little python knowledge can use it well in AirtestIDE. it would be better not to add this for flake8 test. Maybe ignore `playground/test_blackjack.air` in travis.yml is a better idea.

**Comment by Meteorix** [comment]
[``playground/test_blackjack.air``](https://github.com/AirtestProject/Airtest/tree/master/playground/test_blackjack.air) serves as an example for airtest.cli
[``playground/pure_python_example``](https://github.com/AirtestProject/Airtest/tree/master/playground/pure_python_example) serves as more pythonic example

**Comment by cclauss** [comment]
https://travis-ci.org/AirtestProject/Airtest/builds/360152174

**Comment by cclauss** [comment]
https://travis-ci.org/AirtestProject/Airtest/pull_requests

**Comment by Meteorix** [comment]
@cclauss fix it with this: https://travis-ci.org/AirtestProject/Airtest/builds/360159739

**Pull request closed without merging**
